version: "3.1"
volumes:
  postgres: ~
  yarn_cache:
services:
  nginx:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ./docker/hosts/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/hosts/symfony:/etc/nginx/symfony
    ports:
      - "${NGINX_PORT}:80"
    links:
      - php
  postgres:
    ports:  #Нельзя использовать проброс портов на реальном проекте
      - "127.0.0.1:5432:5432"
    image: postgres:alpine
    shm_size: '2gb'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
  php:
    build: docker/images/php
    working_dir: /app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${PWD}:/app
      - ${HOME}/.composer:/.composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    links:
      - postgres
  node:
    image: node:alpine
    environment:
      - YARN_CACHE_FOLDER=/tmp/yarn-cache  # Используем временную директорию
    working_dir: /app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${PWD}:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null
networks:
  default:
    external:
      name: study-billing_default
