name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql
          coverage: pcov
          tools: composer

      - name: Setting environment and composer
        run: |
          echo "DATABASE_URL=pgsql://pguser:pguser@postgres:5432/study_on" >> .env.local
          composer install

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Docker services
        run: |
          mkdir -p ~/.yarn
          docker network create study-billing_default || true
          docker-compose build
          docker-compose up -d
          sleep 15

      - name: Install Node dependencies
        run: |
          # Устанавливаем права на ключевые файлы
          docker-compose exec -T -u root node sh -c "
          mkdir -p /app/node_modules &&
          touch /app/yarn.lock &&
          chown -R node:node /app/node_modules /app/yarn.lock /app/package.json /app/public /app/package-lock.json
          "
          
          docker-compose exec -T node npm install @hotwired/stimulus@^3.0 --save-dev
          docker-compose exec -T node npm install
          docker-compose exec -T node npm run dev
          docker-compose run -u root node yarn install 
          
          # Сборка ассетов
          docker-compose exec -T -u node node yarn encore dev

      - name: Fix console permissions
        run: |
          # Меняем владельца и права через root в контейнере
          docker-compose exec -T --user root php bash -c "chown www-data:www-data /app/bin/console && chmod 755 /app/bin/console"
          # Проверяем
          docker-compose exec -T php ls -la /app/bin/console
      - name: Setting test environment and DB
        run: |
          echo "DATABASE_URL=pgsql://pguser:pguser@postgres:5432/study_on_test" >> .env.test.local
          docker-compose exec -T php bin/console doctrine:database:drop --force --env=test || true
          docker-compose exec -T php bin/console doctrine:database:create --env=test
          docker-compose exec -T php bin/console doctrine:migrations:migrate -n --env=test
          docker-compose exec -T php bin/console doctrine:fixtures:load -n --env=test

      - name: Run PHPUnit
        run: |
          docker-compose exec -T php bin/phpunit
