name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql  # Исправлено на pdo_pgsql
          coverage: pcov
          tools: composer

      - name: Setting environment and composer
        run: |
          echo "DATABASE_URL=pgsql://pguser:pguser@postgres:5432/study_on" >> .env.local
          composer install

      - name: Setting Docker
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          mkdir ~/.yarn
          docker network create study-billing_default
          docker-compose build
          docker-compose up -d
          
          # Установка специфичных зависимостей
          docker-compose exec -T --user root node bash -c "yarn add @symfony/stimulus-bundle @hotwired/stimulus --dev"
          
          # Основная установка зависимостей
          docker-compose run -u root node yarn install --force --network-timeout 1000000
          
          # Сборка ассетов
          docker-compose run -u root node yarn encore dev

      - name: Fix permissions
        run: |
          docker-compose exec -T --user root php bash -c "chown www-data:www-data /app/bin/console && chmod 755 /app/bin/console"
          docker-compose exec -T --user root php bash -c "chmod +x /app/bin/phpunit && chown www-data:www-data /app/bin/phpunit"

      - name: Clear cache
        run: |
          docker-compose exec -T php bin/console cache:clear --env=test

      - name: Setting test environment and DB
        run: |
          echo "DATABASE_URL=pgsql://pguser:pguser@postgres:5432/study_on_test" >> .env.test.local
          docker-compose exec -T --user www-data php bin/console doctrine:database:drop --force --env=test || true
          docker-compose exec -T --user www-data php bin/console doctrine:database:create --env=test
          docker-compose exec -T --user www-data php bin/console doctrine:migrations:migrate -n --env=test
          docker-compose exec -T --user www-data php bin/console doctrine:fixtures:load -n --env=test

      - name: Run PHPUnit
        run: |
          docker-compose exec -T php bin/phpunit
